# Generated by Django 5.2.5 on 2025-08-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matriz",
            options={"verbose_name": "Matriz", "verbose_name_plural": "Matrizes"},
        ),
        migrations.RenameField(
            model_name="matriz",
            old_name="descrição",
            new_name="descricao",
        ),
    ]
