# Generated by Django 5.2 on 2025-08-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0002_alter_matriz_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apelido",
                    models.CharField(
                        help_text="Apelido ou abreviação",
                        max_length=200,
                        verbose_name="Apelido",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(
                        help_text="Razão social da empresa",
                        max_length=200,
                        verbose_name="Razão Social",
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        help_text="Endereço completo",
                        max_length=200,
                        verbose_name="Endereço",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        help_text="Telefone para contato",
                        max_length=15,
                        verbose_name="Telefone/Fax",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        help_text="CNPJ", max_length=20, verbose_name="CNPJ"
                    ),
                ),
                (
                    "tipo_empresa",
                    models.CharField(
                        choices=[
                            ("CONSULTORIA", "Consultoria Ambiental"),
                            ("CLIENTE", "Cliente"),
                            ("FORNECEDOR", "Fornecedor"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Empresa",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Endereço de e-mail",
                        max_length=254,
                        null=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "responsavel_tecnico",
                    models.CharField(
                        blank=True,
                        help_text="Responsável técnico (apenas para clientes)",
                        max_length=80,
                        null=True,
                        verbose_name="Responsável Técnico",
                    ),
                ),
            ],
        ),
    ]
