# Generated by Django 5.2 on 2025-08-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0003_empresa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Parametro",
            },
        ),
    ]
