# Generated by Django 5.2 on 2025-08-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0004_parametro"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametro",
            name="unidade_medida",
            field=models.CharField(
                default="mg/L",
                help_text="Unidade de medida",
                max_length=10,
                verbose_name="Unidade",
            ),
            preserve_default=False,
        ),
    ]
