# Generated by Django 5.2 on 2025-09-03 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0005_parametro_unidade_medida"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100, unique=True)),
                (
                    "matriz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simplims_app.matriz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço",
            },
        ),
    ]
