# Generated by Django 5.2 on 2025-09-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0007_ordemservico"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amostra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Volume",
                    ),
                ),
                ("horario_coleta", models.TimeField(verbose_name="Horário da Coleta")),
                (
                    "local_coleta",
                    models.CharField(max_length=200, verbose_name="Local da Coleta"),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="pH",
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Temperatura (°C)",
                    ),
                ),
                (
                    "solidos_sedimentaveis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=7,
                        null=True,
                        verbose_name="Sólidos Sedimentáveis (mL/L)",
                    ),
                ),
                (
                    "materiais_flutuantes",
                    models.BooleanField(
                        default=False, verbose_name="Materiais Flutuantes"
                    ),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amostras",
                        to="simplims_app.ordemservico",
                        verbose_name="Ordem de Serviço",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simplims_app.servico",
                        verbose_name="Serviço Contratado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoAmostraParametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Resultado"
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Unidade"
                    ),
                ),
                (
                    "data_analise",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Análise"
                    ),
                ),
                (
                    "amostra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="simplims_app.amostra",
                        verbose_name="Amostra",
                    ),
                ),
                (
                    "parametro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simplims_app.parametro",
                        verbose_name="Parâmetro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de Parâmetro da Amostra",
                "verbose_name_plural": "Resultados de Parâmetros das Amostras",
                "unique_together": {("amostra", "parametro")},
            },
        ),
    ]
