# Generated by Django 5.2 on 2025-09-10 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0008_amostra_resultadoamostraparametro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Legislacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_minimo", models.FloatField(blank=True, null=True)),
                ("valor_maximo", models.FloatField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "parametro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simplims_app.parametro",
                    ),
                ),
            ],
        ),
    ]
