# Generated by Django 5.2 on 2025-09-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0009_legislacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoParametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
