# Generated by Django 5.2 on 2025-09-11 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0011_categoriaparametro"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametro",
            name="categoria_parametro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="simplims_app.categoriaparametro",
            ),
        ),
        migrations.AddField(
            model_name="parametro",
            name="tipo_parametro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="simplims_app.tipoparametro",
            ),
        ),
    ]
