# Generated by Django 5.2 on 2025-09-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0012_parametro_categoria_parametro_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="resultadoamostraparametro",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="amostra",
            name="ordem_servico",
        ),
        migrations.RemoveField(
            model_name="amostra",
            name="servico",
        ),
    ]
