# Generated by Django 5.2 on 2025-09-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "simplims_app",
            "0013_alter_resultadoamostraparametro_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultadoamostraparametro",
            name="amostra",
        ),
        migrations.RemoveField(
            model_name="resultadoamostraparametro",
            name="parametro",
        ),
        migrations.DeleteModel(
            name="Amostra",
        ),
        migrations.DeleteModel(
            name="ResultadoAmostraParametro",
        ),
    ]
