# Generated by Django 5.2 on 2025-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0014_remove_resultadoamostraparametro_amostra_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametro",
            name="descricao",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="parametro",
            unique_together={("descricao", "unidade_medida")},
        ),
    ]
