# Generated by Django 5.2 on 2025-09-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0015_alter_parametro_descricao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legislacao",
            name="valor_minimo",
        ),
        migrations.AlterField(
            model_name="parametro",
            name="unidade_medida",
            field=models.CharField(max_length=10, verbose_name="Unidade de Medida"),
        ),
    ]
