# Generated by Django 5.2 on 2025-09-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0016_remove_legislacao_valor_minimo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="apelido",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="cnpj",
            field=models.CharField(max_length=20, verbose_name="CNPJ"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="endereco",
            field=models.CharField(max_length=200, verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="razao_social",
            field=models.CharField(max_length=200, verbose_name="Razão Social"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="responsavel_tecnico",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="Responsável Técnico"
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="telefone",
            field=models.CharField(max_length=15, verbose_name="Telefone/Fax"),
        ),
    ]
