# Generated by Django 5.2 on 2025-10-02 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0017_alter_empresa_apelido_alter_empresa_cnpj_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitaTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_visita", models.DateField(verbose_name="Data da Visita")),
                (
                    "hora_visita",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora da Visita"
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        help_text="Endereço ou ponto de coleta",
                        max_length=255,
                        verbose_name="Local da Visita",
                    ),
                ),
                ("responsavel", models.CharField(max_length=100)),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("REALIZADA", "Realizada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status do Agendamento",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simplims_app.ordemservico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visita Técnica",
                "verbose_name_plural": "Visitas Técnicas",
                "ordering": ["-data_visita", "-hora_visita"],
            },
        ),
    ]
