# Generated by Django 5.2 on 2025-10-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0017_alter_empresa_apelido_alter_empresa_cnpj_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordemservico",
            name="servico",
        ),
    ]
