# Generated by Django 5.2 on 2025-10-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0018_remove_ordemservico_servico"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="servicos",
            field=models.ManyToManyField(
                help_text="Selecione os serviços desta OS",
                to="simplims_app.servico",
                verbose_name="Serviços contratados",
            ),
        ),
    ]
