# Generated by Django 5.2 on 2025-10-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0019_ordemservico_servicos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordemservico",
            name="matriz",
        ),
    ]
