# Generated by Django 5.2 on 2025-10-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0018_visitatecnica"),
        ("simplims_app", "0020_remove_ordemservico_matriz"),
    ]

    operations = []
