# Generated by Django 5.2 on 2025-10-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0021_merge_20251029_2118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitatecnica",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("CONFIRMADA", "Confirmada"),
                    ("REALIZADA", "Realizada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="PENDENTE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
