# Generated by Django 5.2 on 2025-10-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0022_alter_visitatecnica_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordemservico",
            name="quantidade_amostras",
        ),
    ]
