# Generated by Django 5.2 on 2025-10-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0023_remove_ordemservico_quantidade_amostras"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="resultados_servicos",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
